build_and_push:
  stage: build
  image: docker:latest

  services:
    - docker:dind

  only:
    refs:
      - main
    changes:
      - pi-docker/**
      - .gitlab-ci.yml

  variables:
    DOCKER_IMAGE: sullivanhart/pi-docker
    DOCKER_TAG_LATEST: latest
    DOCKER_TAG_COMMIT: $CI_COMMIT_SHORT_SHA

  before_script:
    - docker login -u $DOCKER_USERNAME_PI -p $DOCKER_PASS_PI

  script:
    - docker buildx create --use
    - docker buildx build \
      --platform linux/arm64 \
      -t $DOCKER_IMAGE:$DOCKER_TAG_LATEST \
      -t $DOCKER_IMAGE:$DOCKER_TAG_COMMIT \
      --push \
      ./pi-docker
