image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - push

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - echo "$DOCKER_PASS_PI" | docker login -u "$DOCKER_USERNAME_PI" --password-stdin
  - docker buildx create --use
  - docker buildx inspect --bootstrap

build-job:
  stage: build
  script:
    - echo "Building successful"

test-job:
  stage: test
  script:
    - echo "Testing successful"

push-job:
  stage: push
  script:
    - echo "Pushing successful"
