stages:
  - build
  - test
  - push

build-job:
  stage: build
  script:
    - echo "Building successful"

test-job:
  stage: test
  script:
    - echo "Testing successful"

push-job:
  stage: push
  script:
    - echo "Pushing successful"
