name: Build and Deploys Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "pi-docker/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_PI }}
          password: ${{ secrets.DOCKER_PASS_PI }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./pi-docker
          file: ./pi-docker/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            sullivanhart/pi-docker:latest
            sullivanhart/pi-docker:${{ github.sha }}

      - name: Notify Discord on success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                     \"content\": \"✅ **Build succeeded** for [\`${{ github.repository }}\`](${{ github.server_url }}/${{ github.repository }})\nCommit: [\`${{ github.sha }}\`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})\nAuthor: ${{ github.actor }}\nMessage: _${{ github.event.head_commit.message }}_\" 
                   }" \
               ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord on failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                     \"content\": \"❌ **Build failed** for [\`${{ github.repository }}\`](${{ github.server_url }}/${{ github.repository }})\nCommit: [\`${{ github.sha }}\`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})\nAuthor: ${{ github.actor }}\nMessage: _${{ github.event.head_commit.message }}_\" 
                   }" \
               ${{ secrets.DISCORD_WEBHOOK }}
