name: Build and Deploys Docker Image

on:
  push:
    branches:
      - main
      - pi-http-init
    paths:
      - "pi-docker/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_PI }}
          password: ${{ secrets.DOCKER_PASS_PI }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./pi-docker
          file: ./pi-docker/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            sullivanhart/pi-docker:latest
            sullivanhart/pi-docker:${{ github.sha }}

      - name: Notify Discord on success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                     \"content\": \"✅ Build succeeded for ${GITHUB_REPOSITORY}\nCommit: ${GITHUB_SHA}\nAuthor: ${GITHUB_ACTOR}\nMessage: ${{ github.event.head_commit.message }}\"
                    }" \
               ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord on failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                     \"content\": \"❌ **Build failed** for ${GITHUB_REPOSITORY}\nCommit: ${GITHUB_SHA}\nAuthor: ${GITHUB_ACTOR}\nMessage: ${{ github.event.head_commit.message }}\"
                   }" \
               ${{ secrets.DISCORD_WEBHOOK }}
